name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up java for tests execution
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle - build & test
        run: gradle build